/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "./ngap.16_8.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_ProtocolIE_Container_H_
#define	_NGAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_PDUSessionResourceSetupRequestIEs;
struct NGAP_PDUSessionResourceSetupResponseIEs;
struct NGAP_PDUSessionResourceReleaseCommandIEs;
struct NGAP_PDUSessionResourceReleaseResponseIEs;
struct NGAP_PDUSessionResourceModifyRequestIEs;
struct NGAP_PDUSessionResourceModifyResponseIEs;
struct NGAP_PDUSessionResourceNotifyIEs;
struct NGAP_PDUSessionResourceModifyIndicationIEs;
struct NGAP_PDUSessionResourceModifyConfirmIEs;
struct NGAP_InitialContextSetupRequestIEs;
struct NGAP_InitialContextSetupResponseIEs;
struct NGAP_InitialContextSetupFailureIEs;
struct NGAP_UEContextReleaseRequest_IEs;
struct NGAP_UEContextReleaseCommand_IEs;
struct NGAP_UEContextReleaseComplete_IEs;
struct NGAP_UEContextResumeRequestIEs;
struct NGAP_UEContextResumeResponseIEs;
struct NGAP_UEContextResumeFailureIEs;
struct NGAP_UEContextSuspendRequestIEs;
struct NGAP_UEContextSuspendResponseIEs;
struct NGAP_UEContextSuspendFailureIEs;
struct NGAP_UEContextModificationRequestIEs;
struct NGAP_UEContextModificationResponseIEs;
struct NGAP_UEContextModificationFailureIEs;
struct NGAP_RRCInactiveTransitionReportIEs;
struct NGAP_RetrieveUEInformationIEs;
struct NGAP_UEInformationTransferIEs;
struct NGAP_RANCPRelocationIndicationIEs;
struct NGAP_HandoverRequiredIEs;
struct NGAP_HandoverCommandIEs;
struct NGAP_HandoverPreparationFailureIEs;
struct NGAP_HandoverRequestIEs;
struct NGAP_HandoverRequestAcknowledgeIEs;
struct NGAP_HandoverFailureIEs;
struct NGAP_HandoverNotifyIEs;
struct NGAP_PathSwitchRequestIEs;
struct NGAP_PathSwitchRequestAcknowledgeIEs;
struct NGAP_PathSwitchRequestFailureIEs;
struct NGAP_HandoverCancelIEs;
struct NGAP_HandoverCancelAcknowledgeIEs;
struct NGAP_HandoverSuccessIEs;
struct NGAP_UplinkRANEarlyStatusTransferIEs;
struct NGAP_DownlinkRANEarlyStatusTransferIEs;
struct NGAP_UplinkRANStatusTransferIEs;
struct NGAP_DownlinkRANStatusTransferIEs;
struct NGAP_PagingIEs;
struct NGAP_InitialUEMessage_IEs;
struct NGAP_DownlinkNASTransport_IEs;
struct NGAP_UplinkNASTransport_IEs;
struct NGAP_NASNonDeliveryIndication_IEs;
struct NGAP_RerouteNASRequest_IEs;
struct NGAP_NGSetupRequestIEs;
struct NGAP_NGSetupResponseIEs;
struct NGAP_NGSetupFailureIEs;
struct NGAP_RANConfigurationUpdateIEs;
struct NGAP_RANConfigurationUpdateAcknowledgeIEs;
struct NGAP_RANConfigurationUpdateFailureIEs;
struct NGAP_AMFConfigurationUpdateIEs;
struct NGAP_AMFConfigurationUpdateAcknowledgeIEs;
struct NGAP_AMFConfigurationUpdateFailureIEs;
struct NGAP_AMFStatusIndicationIEs;
struct NGAP_NGResetIEs;
struct NGAP_NGResetAcknowledgeIEs;
struct NGAP_ErrorIndicationIEs;
struct NGAP_OverloadStartIEs;
struct NGAP_OverloadStopIEs;
struct NGAP_UplinkRANConfigurationTransferIEs;
struct NGAP_DownlinkRANConfigurationTransferIEs;
struct NGAP_WriteReplaceWarningRequestIEs;
struct NGAP_WriteReplaceWarningResponseIEs;
struct NGAP_PWSCancelRequestIEs;
struct NGAP_PWSCancelResponseIEs;
struct NGAP_PWSRestartIndicationIEs;
struct NGAP_PWSFailureIndicationIEs;
struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkUEAssociatedNRPPaTransportIEs;
struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_TraceStartIEs;
struct NGAP_TraceFailureIndicationIEs;
struct NGAP_DeactivateTraceIEs;
struct NGAP_CellTrafficTraceIEs;
struct NGAP_LocationReportingControlIEs;
struct NGAP_LocationReportingFailureIndicationIEs;
struct NGAP_LocationReportIEs;
struct NGAP_UETNLABindingReleaseRequestIEs;
struct NGAP_UERadioCapabilityInfoIndicationIEs;
struct NGAP_UERadioCapabilityCheckRequestIEs;
struct NGAP_UERadioCapabilityCheckResponseIEs;
struct NGAP_SecondaryRATDataUsageReportIEs;
struct NGAP_UplinkRIMInformationTransferIEs;
struct NGAP_DownlinkRIMInformationTransferIEs;
struct NGAP_ConnectionEstablishmentIndicationIEs;
struct NGAP_UERadioCapabilityIDMappingRequestIEs;
struct NGAP_UERadioCapabilityIDMappingResponseIEs;
struct NGAP_AMFCPRelocationIndicationIEs;
struct NGAP_PDUSessionResourceModifyRequestTransferIEs;
struct NGAP_PDUSessionResourceSetupRequestTransferIEs;

/* NGAP_ProtocolIE-Container */
typedef struct NGAP_ProtocolIE_Container_9575P0 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P0_t;
typedef struct NGAP_ProtocolIE_Container_9575P1 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P1_t;
typedef struct NGAP_ProtocolIE_Container_9575P2 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P2_t;
typedef struct NGAP_ProtocolIE_Container_9575P3 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P3_t;
typedef struct NGAP_ProtocolIE_Container_9575P4 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P4_t;
typedef struct NGAP_ProtocolIE_Container_9575P5 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P5_t;
typedef struct NGAP_ProtocolIE_Container_9575P6 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P6_t;
typedef struct NGAP_ProtocolIE_Container_9575P7 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P7_t;
typedef struct NGAP_ProtocolIE_Container_9575P8 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P8_t;
typedef struct NGAP_ProtocolIE_Container_9575P9 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P9_t;
typedef struct NGAP_ProtocolIE_Container_9575P10 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P10_t;
typedef struct NGAP_ProtocolIE_Container_9575P11 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P11_t;
typedef struct NGAP_ProtocolIE_Container_9575P12 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P12_t;
typedef struct NGAP_ProtocolIE_Container_9575P13 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P13_t;
typedef struct NGAP_ProtocolIE_Container_9575P14 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P14_t;
typedef struct NGAP_ProtocolIE_Container_9575P15 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P15_t;
typedef struct NGAP_ProtocolIE_Container_9575P16 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P16_t;
typedef struct NGAP_ProtocolIE_Container_9575P17 {
	A_SEQUENCE_OF(struct NGAP_UEContextResumeFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P17_t;
typedef struct NGAP_ProtocolIE_Container_9575P18 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P18_t;
typedef struct NGAP_ProtocolIE_Container_9575P19 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P19_t;
typedef struct NGAP_ProtocolIE_Container_9575P20 {
	A_SEQUENCE_OF(struct NGAP_UEContextSuspendFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P20_t;
typedef struct NGAP_ProtocolIE_Container_9575P21 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P21_t;
typedef struct NGAP_ProtocolIE_Container_9575P22 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P22_t;
typedef struct NGAP_ProtocolIE_Container_9575P23 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P23_t;
typedef struct NGAP_ProtocolIE_Container_9575P24 {
	A_SEQUENCE_OF(struct NGAP_RRCInactiveTransitionReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P24_t;
typedef struct NGAP_ProtocolIE_Container_9575P25 {
	A_SEQUENCE_OF(struct NGAP_RetrieveUEInformationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P25_t;
typedef struct NGAP_ProtocolIE_Container_9575P26 {
	A_SEQUENCE_OF(struct NGAP_UEInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P26_t;
typedef struct NGAP_ProtocolIE_Container_9575P27 {
	A_SEQUENCE_OF(struct NGAP_RANCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P27_t;
typedef struct NGAP_ProtocolIE_Container_9575P28 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P28_t;
typedef struct NGAP_ProtocolIE_Container_9575P29 {
	A_SEQUENCE_OF(struct NGAP_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P29_t;
typedef struct NGAP_ProtocolIE_Container_9575P30 {
	A_SEQUENCE_OF(struct NGAP_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P30_t;
typedef struct NGAP_ProtocolIE_Container_9575P31 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P31_t;
typedef struct NGAP_ProtocolIE_Container_9575P32 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P32_t;
typedef struct NGAP_ProtocolIE_Container_9575P33 {
	A_SEQUENCE_OF(struct NGAP_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P33_t;
typedef struct NGAP_ProtocolIE_Container_9575P34 {
	A_SEQUENCE_OF(struct NGAP_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P34_t;
typedef struct NGAP_ProtocolIE_Container_9575P35 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P35_t;
typedef struct NGAP_ProtocolIE_Container_9575P36 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P36_t;
typedef struct NGAP_ProtocolIE_Container_9575P37 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P37_t;
typedef struct NGAP_ProtocolIE_Container_9575P38 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P38_t;
typedef struct NGAP_ProtocolIE_Container_9575P39 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P39_t;
typedef struct NGAP_ProtocolIE_Container_9575P40 {
	A_SEQUENCE_OF(struct NGAP_HandoverSuccessIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P40_t;
typedef struct NGAP_ProtocolIE_Container_9575P41 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P41_t;
typedef struct NGAP_ProtocolIE_Container_9575P42 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P42_t;
typedef struct NGAP_ProtocolIE_Container_9575P43 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P43_t;
typedef struct NGAP_ProtocolIE_Container_9575P44 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P44_t;
typedef struct NGAP_ProtocolIE_Container_9575P45 {
	A_SEQUENCE_OF(struct NGAP_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P45_t;
typedef struct NGAP_ProtocolIE_Container_9575P46 {
	A_SEQUENCE_OF(struct NGAP_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P46_t;
typedef struct NGAP_ProtocolIE_Container_9575P47 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P47_t;
typedef struct NGAP_ProtocolIE_Container_9575P48 {
	A_SEQUENCE_OF(struct NGAP_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P48_t;
typedef struct NGAP_ProtocolIE_Container_9575P49 {
	A_SEQUENCE_OF(struct NGAP_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P49_t;
typedef struct NGAP_ProtocolIE_Container_9575P50 {
	A_SEQUENCE_OF(struct NGAP_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P50_t;
typedef struct NGAP_ProtocolIE_Container_9575P51 {
	A_SEQUENCE_OF(struct NGAP_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P51_t;
typedef struct NGAP_ProtocolIE_Container_9575P52 {
	A_SEQUENCE_OF(struct NGAP_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P52_t;
typedef struct NGAP_ProtocolIE_Container_9575P53 {
	A_SEQUENCE_OF(struct NGAP_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P53_t;
typedef struct NGAP_ProtocolIE_Container_9575P54 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P54_t;
typedef struct NGAP_ProtocolIE_Container_9575P55 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P55_t;
typedef struct NGAP_ProtocolIE_Container_9575P56 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P56_t;
typedef struct NGAP_ProtocolIE_Container_9575P57 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P57_t;
typedef struct NGAP_ProtocolIE_Container_9575P58 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P58_t;
typedef struct NGAP_ProtocolIE_Container_9575P59 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P59_t;
typedef struct NGAP_ProtocolIE_Container_9575P60 {
	A_SEQUENCE_OF(struct NGAP_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P60_t;
typedef struct NGAP_ProtocolIE_Container_9575P61 {
	A_SEQUENCE_OF(struct NGAP_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P61_t;
typedef struct NGAP_ProtocolIE_Container_9575P62 {
	A_SEQUENCE_OF(struct NGAP_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P62_t;
typedef struct NGAP_ProtocolIE_Container_9575P63 {
	A_SEQUENCE_OF(struct NGAP_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P63_t;
typedef struct NGAP_ProtocolIE_Container_9575P64 {
	A_SEQUENCE_OF(struct NGAP_OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P64_t;
typedef struct NGAP_ProtocolIE_Container_9575P65 {
	A_SEQUENCE_OF(struct NGAP_OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P65_t;
typedef struct NGAP_ProtocolIE_Container_9575P66 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P66_t;
typedef struct NGAP_ProtocolIE_Container_9575P67 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P67_t;
typedef struct NGAP_ProtocolIE_Container_9575P68 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P68_t;
typedef struct NGAP_ProtocolIE_Container_9575P69 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P69_t;
typedef struct NGAP_ProtocolIE_Container_9575P70 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P70_t;
typedef struct NGAP_ProtocolIE_Container_9575P71 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P71_t;
typedef struct NGAP_ProtocolIE_Container_9575P72 {
	A_SEQUENCE_OF(struct NGAP_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P72_t;
typedef struct NGAP_ProtocolIE_Container_9575P73 {
	A_SEQUENCE_OF(struct NGAP_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P73_t;
typedef struct NGAP_ProtocolIE_Container_9575P74 {
	A_SEQUENCE_OF(struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P74_t;
typedef struct NGAP_ProtocolIE_Container_9575P75 {
	A_SEQUENCE_OF(struct NGAP_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P75_t;
typedef struct NGAP_ProtocolIE_Container_9575P76 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P76_t;
typedef struct NGAP_ProtocolIE_Container_9575P77 {
	A_SEQUENCE_OF(struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P77_t;
typedef struct NGAP_ProtocolIE_Container_9575P78 {
	A_SEQUENCE_OF(struct NGAP_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P78_t;
typedef struct NGAP_ProtocolIE_Container_9575P79 {
	A_SEQUENCE_OF(struct NGAP_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P79_t;
typedef struct NGAP_ProtocolIE_Container_9575P80 {
	A_SEQUENCE_OF(struct NGAP_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P80_t;
typedef struct NGAP_ProtocolIE_Container_9575P81 {
	A_SEQUENCE_OF(struct NGAP_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P81_t;
typedef struct NGAP_ProtocolIE_Container_9575P82 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P82_t;
typedef struct NGAP_ProtocolIE_Container_9575P83 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P83_t;
typedef struct NGAP_ProtocolIE_Container_9575P84 {
	A_SEQUENCE_OF(struct NGAP_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P84_t;
typedef struct NGAP_ProtocolIE_Container_9575P85 {
	A_SEQUENCE_OF(struct NGAP_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P85_t;
typedef struct NGAP_ProtocolIE_Container_9575P86 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P86_t;
typedef struct NGAP_ProtocolIE_Container_9575P87 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P87_t;
typedef struct NGAP_ProtocolIE_Container_9575P88 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P88_t;
typedef struct NGAP_ProtocolIE_Container_9575P89 {
	A_SEQUENCE_OF(struct NGAP_SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P89_t;
typedef struct NGAP_ProtocolIE_Container_9575P90 {
	A_SEQUENCE_OF(struct NGAP_UplinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P90_t;
typedef struct NGAP_ProtocolIE_Container_9575P91 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P91_t;
typedef struct NGAP_ProtocolIE_Container_9575P92 {
	A_SEQUENCE_OF(struct NGAP_ConnectionEstablishmentIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P92_t;
typedef struct NGAP_ProtocolIE_Container_9575P93 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityIDMappingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P93_t;
typedef struct NGAP_ProtocolIE_Container_9575P94 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityIDMappingResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P94_t;
typedef struct NGAP_ProtocolIE_Container_9575P95 {
	A_SEQUENCE_OF(struct NGAP_AMFCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P95_t;
typedef struct NGAP_ProtocolIE_Container_9575P96 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P96_t;
typedef struct NGAP_ProtocolIE_Container_9575P97 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_9575P97_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P0;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P0_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P0_1[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P1;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P1_specs_3;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P1_3[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P2;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P2_specs_5;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P2_5[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P3;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P3_specs_7;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P3_7[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P4;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P4_specs_9;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P4_9[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P5;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P5_specs_11;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P5_11[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P6;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P6_specs_13;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P6_13[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P7;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P7_specs_15;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P7_15[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P8;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P8_specs_17;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P8_17[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P9;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P9_specs_19;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P9_19[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P10;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P10_specs_21;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P10_21[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P11;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P11_specs_23;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P11_23[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P12;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P12_specs_25;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P12_25[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P13;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P13_specs_27;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P13_27[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P14;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P14_specs_29;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P14_29[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P15;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P15_specs_31;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P15_31[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P16;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P16_specs_33;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P16_33[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P17;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P17_specs_35;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P17_35[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P18;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P18_specs_37;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P18_37[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P19;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P19_specs_39;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P19_39[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P20;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P20_specs_41;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P20_41[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P21;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P21_specs_43;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P21_43[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P22;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P22_specs_45;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P22_45[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P23;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P23_specs_47;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P23_47[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P24;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P24_specs_49;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P24_49[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P25;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P25_specs_51;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P25_51[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P26;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P26_specs_53;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P26_53[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P27;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P27_specs_55;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P27_55[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P28;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P28_specs_57;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P28_57[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P29;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P29_specs_59;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P29_59[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P30;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P30_specs_61;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P30_61[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P31;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P31_specs_63;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P31_63[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P32;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P32_specs_65;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P32_65[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P33;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P33_specs_67;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P33_67[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P34;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P34_specs_69;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P34_69[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P35;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P35_specs_71;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P35_71[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P36;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P36_specs_73;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P36_73[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P37;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P37_specs_75;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P37_75[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P38;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P38_specs_77;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P38_77[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P39;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P39_specs_79;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P39_79[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P40;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P40_specs_81;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P40_81[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P41;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P41_specs_83;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P41_83[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P42;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P42_specs_85;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P42_85[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P43;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P43_specs_87;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P43_87[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P44;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P44_specs_89;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P44_89[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P45;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P45_specs_91;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P45_91[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P46;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P46_specs_93;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P46_93[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P47;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P47_specs_95;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P47_95[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P48;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P48_specs_97;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P48_97[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P49;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P49_specs_99;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P49_99[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P50;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P50_specs_101;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P50_101[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P51;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P51_specs_103;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P51_103[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P52;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P52_specs_105;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P52_105[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P53;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P53_specs_107;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P53_107[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P54;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P54_specs_109;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P54_109[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P55;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P55_specs_111;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P55_111[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P56;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P56_specs_113;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P56_113[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P57;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P57_specs_115;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P57_115[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P58;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P58_specs_117;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P58_117[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P59;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P59_specs_119;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P59_119[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P60;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P60_specs_121;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P60_121[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P61;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P61_specs_123;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P61_123[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P62;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P62_specs_125;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P62_125[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P63;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P63_specs_127;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P63_127[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P64;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P64_specs_129;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P64_129[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P65;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P65_specs_131;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P65_131[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P66;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P66_specs_133;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P66_133[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P67;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P67_specs_135;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P67_135[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P68;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P68_specs_137;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P68_137[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P69;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P69_specs_139;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P69_139[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P70;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P70_specs_141;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P70_141[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P71;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P71_specs_143;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P71_143[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P72;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P72_specs_145;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P72_145[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P73;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P73_specs_147;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P73_147[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P74;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P74_specs_149;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P74_149[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P75;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P75_specs_151;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P75_151[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P76;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P76_specs_153;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P76_153[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P77;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P77_specs_155;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P77_155[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P78;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P78_specs_157;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P78_157[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P79;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P79_specs_159;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P79_159[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P80;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P80_specs_161;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P80_161[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P81;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P81_specs_163;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P81_163[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P82;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P82_specs_165;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P82_165[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P83;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P83_specs_167;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P83_167[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P84;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P84_specs_169;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P84_169[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P85;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P85_specs_171;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P85_171[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P86;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P86_specs_173;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P86_173[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P87;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P87_specs_175;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P87_175[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P88;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P88_specs_177;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P88_177[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P89;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P89_specs_179;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P89_179[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P90;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P90_specs_181;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P90_181[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P91;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P91_specs_183;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P91_183[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P92;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P92_specs_185;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P92_185[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P93;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P93_specs_187;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P93_187[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P94;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P94_specs_189;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P94_189[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P95;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P95_specs_191;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P95_191[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P96;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P96_specs_193;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P96_193[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_9575P97;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_9575P97_specs_195;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_9575P97_195[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_9575P97_constr_195;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
